name: Android CI

on: [pull_request, push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ default, google_apis ]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Running linting checks
        run: ./gradlew runUnitTests

      - name: Running unit tests
        run: ./gradlew runUnitTests

      - name: Running instumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: ${{ matrix.api-level }}
            target: ${{ matrix.target }}
            arch: x86_64
            profile: Nexus 6
            script: ./gradlew runInstrumentationTests

      - name: Build project with Gradle
        run: ./gradlew build
